name: Test Check
on: pull_request

jobs:
  release:
    name: Test Check
    runs-on: ubuntu-latest
    steps:
      - name: 'Git checkout'
        uses: actions/checkout@v2

      - name: 'test'
        uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const commentInfo = {
              ...context.repo,
              issue_number: context.issue.number,
            };

            const signature = "via JJ GitHub Actions 🇵🇱"
            const comment = {
              ...commentInfo,
              body: `👋 Thanks for testing!\n\n${signature}`,
            };

            let commentId;
            try {
              const comments = (await github.issues.listComments(commentInfo)).data;
              for (let i = comments.length; i--; ) {
                const c = comments[i];
                if (comment.user.type === "Bot" && comment.body.includes(signature)) {
                  commentId = c.id;
                  break;
                }
              }
            } catch (e) {
              console.log("Error checking for previous comments: " + e.message);
            }

            if (commentId) {
              try {
                await github.issues.updateComment({
                  ...context.repo,
                  comment_id: commentId,
                  body: comment.body,
                });
              } catch (e) {
                commentId = null;
              }
            }

            if (!commentId) {
              try {
                await github.issues.createComment(comment);
              } catch (e) {
                console.log(`Error creating comment: ${e.message}`);
              }
            }

            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `👋 Thanks for testing!\n\n${signature}`
            })
